### PR TITLE
Adding new links to Play Store and Github

### PR DESCRIPTION
**Pull request by kewp**
Please approve @mraible

### CODE REVIEW

**Comment by mraible** [comment]
@kewp I talked to @LindsayB610 and she said she prefers #2654. The reason is that we don't want to have too many links in the first page or people will leave the tutorial (and might not come back).

**Comment by kewp** [comment]
Well fair enough. Thought I'd get more installs this way :)

**Comment by mraible** [comment]
Closing in favor of #2654.

@kewp When it's updated on the site, I'll send out a tweet and put a link to your app in it. Hopefully, that'll help get more installs.

**Comment by kewp** [comment]
Thank you, that’s kind of you

**Pull request closed without merging**
