### PR TITLE
Point the URLs to 1.3.2

### PR DESCRIPTION
**Pull request by Ujjwalreddy-okta**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@Ujjwalreddy-okta this looks great! One question:should we link to the reference doc at the bottom, a sort of "for more customization" thing?

**Comment by Ujjwalreddy-okta** [comment]
I think we have it at the top, I am not sure if we need more links in the doc?

**Comment by mystiberry-okta** [comment]
We have a link in the reference doc to this guide, but not the other way around. I'm fine with it as is, just wanted to ask to make sure.

**Comment by Ujjwalreddy-okta** [comment]
Gotcha, I thought there was already one. But we can add it if it is not there. I will leave it upto you on the text.

**Comment by mystiberry-okta** [comment]
@Ujjwalreddy-okta I added it as a last section at the bottom. Okay to merge?

**Comment by Ujjwalreddy-okta** [comment]
@mystiberry-okta Great. looks good. Lets merge.

**Pull request merged**
