### PR TITLE
Add docs for the auth js sdk

### PR DESCRIPTION
**Pull request by lboyette-okta**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@lboyette-okta do you want these changes published?

**Comment by lboyette-okta** [comment]
@mystiberry-okta Yes! If these changes could be published, I'd appreciate it. These are beta docs, so they won't be linked anywhere, and more additions will come later, but they are enough to get started with the SDK.

**Comment by mystiberry-okta** [comment]
Will merge now and they'll be published with the new release, since it's coming out today.


Mysti


________________________________

**Comment by lboyette-okta** [comment]
Great, thanks!

**Pull request merged**
