### PR TITLE
Remove old coming soon pages

### PR DESCRIPTION
**Pull request by nbarbettini**
## Description:
Deleted old placeholder pages that were causing problems in search results. I don't think they were linked to anywhere so this shouldn't cause any broken links.

### Resolves:
* [OKTA-139514](https://oktainc.atlassian.net/browse/OKTA-139514)

### CODE REVIEW

**Comment by nbarbettini** [comment]
Ping @mystiberry-okta for review - to make sure I didn't screw something up 😄

**Comment by nbarbettini** [comment]
@mystiberry-okta I don't have permission to merge. Can you press the button?

**Comment by nbarbettini** [comment]
This is currently waiting for me to rebase to weekly. Didn't realize I had to do that first.

**Comment by mystiberry-okta** [comment]
@natebarbettini-okta Can you resolve the conflict of Gemfile.lock? Also, rebase to get rid of the other commits? And lastly, just fyi you have to remove the HTML files as well (unless someone else has already), just removing the .md files won't kill the "last" version of the HTML files, at least it didn't a month ago.

**Comment by mystiberry-okta** [comment]
Will merge as soon as travis checks finish.

**Comment by nbarbettini** [comment]
Rebased to `weekly`.

@mystiberry-okta I don't see a conflict with Gemfile.lock. Might have been a rebase conflict that I just resolved. Good call on the HTML files, I removed them.

If it all looks good to you, merge please 😄

**Pull request merged**
