### PR TITLE
LoginHint for Inbound SAML

### PR DESCRIPTION
**Pull request by yuliu-okta**
## Description:
- Describe your changes. This will most likely be a copy-paste of your commit
  message(s), which should be descriptive and informative.

### Resolves:
* [Issue #X](#X)

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by jakubvul** [comment]
@yuliu-okta please don't ignore the PR template.

**Comment by jakubvul** [comment]
@yuliu-okta our SAML content is now hosted on [okta.com/integrate](https://www.okta.com/integrate/documentation/saml/). You'll need to work with the Web Marketing team to update any content there.

**Comment by johngronberg-okta** [comment]
This pr is for inbound SAML and needs to be on the Dev.okta.com site.


________________________________

**Comment by nbarbettini** [comment]
@yuliu-okta The change to ` _source/_docs/api/resources/idps.md` is 👍. The SAML Standards page has moved to https://www.okta.com/integrate/documentation/saml. Can you remove that update from this PR and work with @jakubvul to get the request over to the team that maintains the new page?

cc @johngronberg-okta

**Pull request closed without merging**
