### PR TITLE
Scrub old pages

### PR DESCRIPTION
**Pull request by rdegges**
Getting rid of the old pages that are no longer used. These pages have been replaced by Drupal.

This is just some cleanup work to scrub these guys.

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@rdegges Why are you removing the OAN landing page? It's not going to drupal is it?

**Comment by rdegges** [comment]
@mystiberry-okta correct. It is in Drupal now.

**Comment by mystiberry-okta** [comment]
And there's no problem with it linking to content in developer.okta.com (the reason for it's existence)? Why was this moved (as opposed to all the other content which wasn't)? Thanks!

**Comment by bdemers** [comment]
@rdegges I just re-targeted this PR to the new `source` branch.

**Comment by jmelberg-okta** [comment]
Closing due to #1439

**Pull request closed without merging**
