### PR TITLE
updated email

### PR DESCRIPTION
**Pull request by dhorvath**
updated from oan@okta.com  --> developers@okta.com

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
Looks great, @dhorvath ! Should I go ahead and merge or is someone else reviewing? There's no JIRA so I'm not sure of the timing.

**Comment by dhorvath** [comment]
@mystiberry-okta great! push it!

**Comment by dhorvath** [comment]
Cool! Should it be real time? Not seeing the changes just yet on the live
site

**Comment by mystiberry-okta** [comment]
Oh, no, I'll need to publish the site again. Won't take long, I'll email you when done.


________________________________

**Comment by mystiberry-okta** [comment]
site refreshed, I see your changes. Since I'm new at this, do let me know if you see anything wrong!


http://developer.okta.com/docs/guides/oan_guidance.html

[https://cloud.githubusercontent.com/assets/3278918/12026582/33986a56-ad70-11e5-96d4-3525cb796367.jpg]<http://developer.okta.com/docs/guides/oan_guidance.html>

Okta Application Network | Okta Developer<http://developer.okta.com/docs/guides/oan_guidance.html>
developer.okta.com
Become a member of the Okta Application Network. Enhance your identity integration and improve adoption with your customers.





Mysti


________________________________

**Pull request merged**
