### PR TITLE
Clarify wording

### PR DESCRIPTION
**Pull request by nbarbettini**
## Description:

This wording is causing confusion for customers, because it sounds like the integrations won't work after the sunset date. Updated to clarify that it simply means no new feature development.

## Type of Pull Request:

- [x] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [ ] Functional (CSS changes, JS updates, or layout modifications)

## How Has This Been Tested?
- [ ] I have built this locally and verified that it does not break existing functionality.
- [ ] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers

@mystiberry-okta @jakubvul-okta @rchild-okta

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@nbarbettini Can they call Okta Support for issues after that date? (Maybe that's stated elsewhere.)

**Comment by nbarbettini** [comment]
@mystiberry-okta Not sure; I think this depends on the level of support a customer has. Do you think that needs to be clarified here?

**Comment by mystiberry-okta** [comment]
@nbarbettini If nothing's different after the end date, then we don't need to say anything.

**Comment by nbarbettini** [comment]
@mystiberry-okta That's my understanding.

**Comment by mystiberry-okta** [comment]
@rchild-okta I merged this  thinking it was 'weekly', I'll do the prod build so we're up to date.

**Pull request merged**
