### PR TITLE
adjust some text for response_mode for authorize call

### PR DESCRIPTION
**Pull request by frankmontanaro-okta**

### CODE REVIEW

**Comment by frankmontanaro-okta** [comment]
@royalchan-okta let me know if this text makes any more sense in the current state of things
cc: @mystiberry-okta

**Comment by royalchan-okta** [comment]
Response Mode query can't be used with `reponse_type=token` either. Specifically, it can only be used with `code`. Otherwise everything else looks good.

**Comment by frankmontanaro-okta** [comment]
k cool updated 'If <em>id_token</em> **or <em>token</em>** is specified as the response type, then <em>query</em> can't be used as the response mode.'

**Comment by mystiberry-okta** [comment]
We already have some caveats/extra info in the "Parameter Details" section below the table (the content itself looks good!). Can I move the caveats down there? I should probably put a link in the current description.

**Comment by royalchan-okta** [comment]
I'm ok either location, whatever you think is best!

**Pull request merged**
