### PR TITLE
First draft idps.md

### PR DESCRIPTION
**Pull request by mystiberry-okta**
@tthompson-okta @karlmcguinness-okta @cwu-okta 
First draft of idps.md. There are 10 TODO's--the "link" ones are for me, but I need help with the rest, especially the last three in the Operations section. Ping me if I should follow up with email about them. 

@larsjohansen-okta you might want to look at the Microsoft references, but there's nothing complicated there.

### CODE REVIEW

**Comment by cwu-okta** [comment]
Nit: typo for
```The Okta Identity Providers API provides operations to manage federations with external Identity Providers (IDP). For example, your app can support logging in with credentials from Facebok, Google, LinkedIn, Microsoft, or an enterprise IdP using SAML 2.0 protocol.```
Should be ```Facebook```

**Comment by cwu-okta** [comment]
```TODO Link The OAuth 2.0 Setup Guide lists the scopes that are supported per-IdP provider.```

Perhaps it is better to have a landing page somewhere in ServiceCloud which lists all of our IdP setup instructions. Then you can link that landing page here.

**Comment by cwu-okta** [comment]
```"href": "https://mysticorp.oktapreview.com/oauth2/v1/authorize?idp=0oa62b57p7c8PaGpU0h7&client_id={clientId}&response_type={responseType}&response_mode={responseMode}&scope={scopes}&redirect_uri={redirectUri}&state={state}",
      "templated": true,
      "hints": {
        "allow": [
          "GET"
        ]
      }
    },
    "clientRedirectUri": {
      "href": "https://mysticorp.oktapreview.com/oauth2/v1/authorize/callback",
```
Should remove mysticorp from the example and replace with generic subdomain

**Comment by mystiberry-okta** [comment]
am waiting until all the samples are in to convert mysticorp.oktapreview so I only have to do it once.

**Comment by mystiberry-okta** [comment]
@tthompson-okta @karlmcguinness-okta @cwu-okta @larsjohansen-okta  I disguised kid, client secrets & ids, fixed bad line breaks, and hid the requests we aren't doc'ing for next week.

**Comment by mystiberry-okta** [comment]
@cwu-okta I think this is ready--but we stashed things yesterday, so I'm unsure how to get 0fba8a0 and 7b96b3e back on my local branch so I can test before merging.

**Comment by mystiberry-okta** [comment]
@karlmcguinness-okta or @tthompson-okta  or @larsjohansen-okta  can someone okay this to ship today?

**Comment by mystiberry-okta** [comment]
@cwu-okta  since these are only cleanup changes, I'll publish at 4pm today if no response.

**Comment by cwu-okta** [comment]
looks ok from my side.

**Comment by mystiberry-okta** [comment]
@tthompson-okta , can you review or say you don't need to? Thanks!

**Comment by tthompson-okta** [comment]
@mystiberry-okta we can't publish the "TODOs". I'm looking at the patch file (https://github.com/okta/okta.github.io/pull/201.patch) and there are still at least four instances of:
`TODO: isn't this read-only?`

**Comment by tthompson-okta** [comment]
There's also a `<!-- To be completed in future release.`

**Comment by mystiberry-okta** [comment]
@tthompson-okta  Apologies for repeated errors (TODOs), I am having trouble still with Git (obviously). Those TODOs are gone in my local copy, I'll get help to figure out what's wrong.

@cwu-okta For the comment, are we not allowed to leave commented stuff in the source? There were some requests that we okay'd doc'ing in a later release. They don't show in the HTML (though it's all there in the page source if you look). I can pull them out if that's our standard. As soon as I figure out how I pushed the wrong version again. sigh.

**Comment by cwu-okta** [comment]
AFAIK we do not have a standard around leaving/removing comments when it comes to doc. I’d suggest discussing with Joel and Evan to see what the standard should be.

**Comment by cwu-okta** [comment]
But I am personally a fan of removing comments and creating a follow up Jira(s) for the work

**Comment by mystiberry-okta** [comment]
@tthompson-okta https://github.com/okta/okta.github.io/pull/201.patch is a diff of each commit. The patch URL doesn't show you a collapsed view of all commits. Instead it shows the diffs per commit. If you scroll toward the bottom, you'll see the TODOs are removed (except the last bit in comments). I sat with Cindy to make sure this branch doesn't contain any TODOs.

**Comment by tthompson-okta** [comment]
looks good, :ship:

**Pull request merged**
