### PR TITLE
remove unsupported URL-encoded auth method

### PR DESCRIPTION
**Pull request by mystiberry-okta**
@larsjohansen-okta  can you check this? should I just remove that whole paragraph?

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
hold off, I forgot to modify that table....

**Comment by mystiberry-okta** [comment]
Okay, @larsjohansen-okta ready for your approval!

**Comment by larsjohansen-okta** [comment]
Looks good to me. 🚢 

Adding @cwu-okta as well.

**Comment by mystiberry-okta** [comment]
@eklein-okta I'm just waiting for one other person to validate this PR. Go ahead and merge it tomorrow if no one responds.

**Comment by cwu-okta** [comment]
Where is the Jira #? Please add and make sure the Jira links back to this PR. 
🚢

**Comment by mystiberry-okta** [comment]
https://oktainc.atlassian.net/browse/OKTA-89514

**Pull request merged**
