### PR TITLE
Doc 104948

### PR DESCRIPTION
**Pull request by mystiberry-okta**
@federations-okta making scopes required in doc per Cindy's request, added labels for beta so you can tell OIDC from OAuth 2.0.

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@federations-okta Can someone review this?

**Comment by danielzeller-okta** [comment]
Why are we putting the beta tags around OpenId Connect? OIDC is EA.

**Comment by mystiberry-okta** [comment]
Great question! I was hiding just the label "OpenID Connect" because if you aren't viewing the Beta, you don't need it (there's only one endpoint you can use). You only need the label if you're viewing the beta version.

**Comment by danielzeller-okta** [comment]
Makes sense. LGTM 🍧

**Comment by mystiberry-okta** [comment]
Merging now, will be published tomorrow.

**Pull request merged**
