### PR TITLE
Fb pjm google tag manager

### PR DESCRIPTION
**Pull request by pauljmartinez**
## Description:
- Fixes to correct errors and warnings thrown by Google Tag Assistant for Google Tag Manager and Google Remarketing code.

## Type of Pull Request:

- [ ] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [x] Functional (CSS changes, JS updates, or layout modifications)

### Resolves:
* n/a (Request from Jamie Lee Rice)

## How Has This Been Tested?
- [x] I have built this locally and verified that it does not break existing functionality.
- [ ] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers:

- *Tag reviewer(s)*

- [Blog Post Google Doc](https://docs.google.com)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
Thank you for the corrections, @pauljmartinez ! 
Status: Mysti to remove extraneous commits, then review.

**Comment by mystiberry-okta** [comment]
@rchild-okta or @jmelberg-okta is this okay to merge?

**Comment by jmelberg-okta** [comment]
@mystiberry-okta: We should sync up with Marketing for this review.

Not sure why we moved the GTM script to the footer -- while the commit says we placed it in the header. GTM scripts are recommended to be included the the main `<header>`

**Comment by mystiberry-okta** [comment]
Pinging JL for help.

**Comment by pauljmartinez** [comment]
Please disregard this PR, I did not include all of the files for this update. Sorry. I'll post a replacement shortly.

**Pull request closed without merging**
