### PR TITLE
Add note about classic vs dev UI

### PR DESCRIPTION
**Pull request by Mark-Hetherington**
Users need to use classic UI to create a SAML app.

## Description:
- Users need to use classic UI to create a SAML app.

### Resolves:
* #1228 - SAML 2.0 not available after clicking "Create New App"

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@Mark-Hetherington Thank you for this doc PR! I'll accept it as soon as it's been reviewed.

**Comment by mraible** [comment]
LGTM 👍

**Comment by mystiberry-okta** [comment]
@Mark-Hetherington Not ignoring your doc PR, we're just making some internal changes. Look for an update next week.

**Comment by mystiberry-okta** [comment]
Because this is a fork, I'm going to merge it, then build source & publish in separate PR.

**Pull request merged**
