### PR TITLE
OKTA-157865 /logs: update page size limit to 1000

### PR DESCRIPTION
**Pull request by ryanoblak-okta**
## Description:
Updates the documented page size limit to 1000 to reflect API change.

**Note: this should not be published until the corresponding code change is deployed.**

### Resolves:
* [OKTA-157865](https://oktainc.atlassian.net/browse/OKTA-157865)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@ryanoblak-okta If this is meant to wait for 2018.08, please base it on `weekly` branch.

**Comment by mystiberry-okta** [comment]
@ryanoblak-okta Please use `weekly` as the base to ensure this isn't pushed early. Also, it looks like you have a conflict resolution that's needed.

**Comment by ryanoblak-okta** [comment]
@mystiberry-okta Will rebase off of `weekly`. The associated API code change is slated to be deployed on the **Sage** 2018.08 release, which is tentatively going to prod on 2/26 (not confirmed by RelEng yet).

**Comment by mystiberry-okta** [comment]
@ryanoblak-okta I'm going to close this since I forgot it was here and repeated the change in this PR: https://github.com/okta/okta.github.io/pull/1799

**Comment by ryanoblak-okta** [comment]
@mystiberry-okta Roger that. Thanks for the heads up :)

**Pull request closed without merging**
