### PR TITLE
Updated New SCIM CRUD Test File

### PR DESCRIPTION
**Pull request by yuvalalter-okta**
## Description:
- Updated Okta-SCIM-CRUD-Test.json from v1.0 to v1.1

### Resolves:

* [OKTA-203053](https://oktainc.atlassian.net/browse/OKTA-203053)

### CODE REVIEW

**Comment by yuvalalter-okta** [comment]
Waiting for @eduardopedayo-okta to confirm with Andrei whether SCIM 2.0 or SCIM 1.1 CRUD file needs to be updated, putting this on hold until then

**Comment by yuvalalter-okta** [comment]
@eduardopedayo-okta @andreiiatiniuc-okta can you please take a look and let me know if the files were updated correctly?

**Comment by jakubvul** [comment]
When should this be merged?

**Comment by yuvalalter-okta** [comment]
@jakubvul this should be merged today, just waiting to make sure everything builds ok after rebase

**Pull request merged**
