### PR TITLE
[DO NOT MERGE] Allow for extra content after first item in change log

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@jakubvul @jakubvul-okta are you using this in the 2018.16+17 release notes? Should we keep this around or is it okay to close?

**Comment by jakubvul** [comment]
I think we should use this, but Demers isn't around to help with it today. Let's merge it for the next release notes?

**Comment by mystiberry-okta** [comment]
Ack.

**Comment by jakubvul** [comment]
I'll get to this once I'm back from PTO.

**Pull request closed without merging**
