### PR TITLE
Update events.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
i added
core.user.factor.activate
are there others to add?

### CODE REVIEW

**Comment by andriyko** [comment]
All the events starting with `app.add.` and `app.ldap.` prefixes are not documented in the docs.
Few examples:
`app.ad.config.agent.agent_created`
`app.ad.agent.start`
`app.ad.agent.user-auth-and-update`
`app.ad.agent.user-auth-and-update.error`
`app.ad.api.user_import.warn.skipped_user.missing_required_attribute`
`app.ldap.agent.reconnected`
`app.ldap.agent.disconnected`
`app.ldap.login.success`

**Comment by gabrielsroka** [comment]
r we planning to add `app.ad.*` and `app.ldap.*` ?

**Comment by mystiberry-okta** [comment]
@gabrielsroka  should I merge this and publish to site? Not sure of the status...

**Comment by gabrielsroka** [comment]
Yes, please. And add Andriy's events and any others.

I'm not sure if any of this is changing for Sys Log 2.0..

**Comment by mystiberry-okta** [comment]
@cwu-okta  Gabriel is requesting more changes but I'm not qualified to make them. Should I create a JIRA for this?

**Comment by cwu-okta** [comment]
@mystiberry-okta yes a Jira should be created for the Directories team and assigned to PM.

**Comment by mystiberry-okta** [comment]
JIRA created: https://oktainc.atlassian.net/browse/OKTA-99642

**Comment by likel** [comment]
@cwu-okta @mystiberry-okta Any update? I can find more MFA events object types:
```
core.user.factor.activate
core.user.factor.attempt_fail
core.user.factor.attempt_success
core.user.factor.deactivate
core.user.factor.reset_all
core.user.factor.update
```

**Comment by mystiberry-okta** [comment]
Created a work request to complete this task, assigned to appropriate team.

**Pull request closed without merging**
