### PR TITLE
removing commented, outdated code

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- Describe your changes. This will most likely be a copy-paste of your commit
  message(s), which should be descriptive and informative.

## Type of Pull Request:

- [ ] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [x] Functional (CSS changes, JS updates, or layout modifications)

### Resolves:
* [OKTA-130667](https://oktainc.atlassian.net/browse/OKTA-130667)

## How Has This Been Tested?
- [x] I have built this locally and verified that it does not break existing functionality.
- [ ] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers:
@jmelberg-okta

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@jmelberg-okta , I removed the commented code after testing locally. Asking you to review since you are familiar.

**Comment by mystiberry-okta** [comment]
@jmelberg-okta I had to merge for the release, but will follow up on any issues you call out.

**Comment by jmelberg-okta** [comment]
@mystiberry-okta Looks like this may alter our page if we have comments enabled. Not sure when that will roll out, but when it does -- we will want to add that script back in.

**Comment by mystiberry-okta** [comment]
Ack, I'll follow up with you.

**Pull request merged**
