### PR TITLE
Add Postman links for /logs

### PR DESCRIPTION
**Pull request by ryanoblak-okta**
**Note**: this PR depends on [PR 723](https://github.com/okta/okta.github.io/pull/723), which itself depends on [PR 722](https://github.com/okta/okta.github.io/pull/722).

Adds Postman links for `/logs` to `api/getting_started/api_test_client`
and `api/resources/system_log`.

The list of collections on `api_test_client` is also alphabetized and
existing Postman links are modified to open in a new tab, rather
than navigating away from Okta docs in the current tab.

### Additions to `system_log`
image

#### Before
screen shot 2017-04-05 at 3 05 40 pm

#### After
image

### Modification of `api_test_client` to avoid leaving Okta docs tab
apr-07-2017 11-28-46

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@ryanoblak-okta Did someone request that you alphabetize the postman collections? We put the auth and oauth/oidc at the top on purpose.

**Comment by mystiberry-okta** [comment]
@ryanoblak-okta One more question--is there a reason to put the target in description of IdP collection?

**Comment by ryanoblak-okta** [comment]
@mystiberry-okta
> Did someone request that you alphabetize the postman collections? We put the auth and oauth/oidc at the top on purpose. Also templates was down in the list and roles (admin roles), also deliberate. I'm happy to go to 100% alpha by label if it was requested by customers. Just not sure if you thought it was random.

I figured there might be some order to it, but wasn't sure ;) If it's ok with you, I'll revert the order with two small changes:
1. Add `Logs` just below `IdP`.
2. Move `Users` above `Custom SMS templates` (I don't really care about this one, but it strikes me as odd to have `Users` below `Custom SMS templates`.

> One more question--is there a reason to put the target in description of IdP collection?
Great catch, thank you! I used a regex to add in the `target` attributes and didn't notice that IdP had a different format.

**Comment by mystiberry-okta** [comment]
Sounds good! The only reason templates is above Users is because it’s really just “Templates” but maybe go ahead and leave it where you put it. So many people look for Roles instead of Admin roles, it’s good to put that one back.

Great work, thank you!

On Apr 7, 2017, at 9:25 AM, ryanoblak-okta <notifications@github.com<mailto:notifications@github.com>> wrote:


@mystiberry-okta<https://github.com/mystiberry-okta>

Did someone request that you alphabetize the postman collections? We put the auth and oauth/oidc at the top on purpose. Also templates was down in the list and roles (admin roles), also deliberate. I'm happy to go to 100% alpha by label if it was requested by customers. Just not sure if you thought it was random.

I figured there might be some order to it, but wasn't sure ;) If it's ok with you, I'll revert the order with two small changes:

  1.  Add Logs just below IdP.
  2.  Move Users above Custom SMS templates (I don't really care about this one, but it strikes me as odd to have Users below Custom SMS templates.

One more question--is there a reason to put the target in description of IdP collection?
Great catch, thank you! I used a regex to add in the target attributes and didn't notice that IdP had a different format.

**Comment by mystiberry-okta** [comment]
tested. waiting to merge until 4/19

**Comment by mystiberry-okta** [comment]
retested on bacon.

**Pull request merged**
