### PR TITLE
Added Python documentation

### PR DESCRIPTION
**Pull request by lboyette-okta**
Added Python to our list of SDKs and added docs. Note: jekyll may not run (it didn't prior to my commit) and the css doesn't load using static pages, so I spin up a small webservice in the repo's root directory.

@tthompson-okta @stsai-okta @croche-okta @rwang-okta @larsjohansen-okta @mohitchugh-okta

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
What's happening with this? Is it still a valid item? @lboyette-okta

**Comment by larsjohansen-okta** [comment]
bump @lboyette-okta

**Comment by larsjohansen-okta** [comment]
bump @lboyette-okta

**Comment by lboyette-okta** [comment]
This is no longer valid, as we already have the Python documentation on developer.okta.com:

http://developer.okta.com/docs/sdk/core/python_api_sdk/

**Pull request closed without merging**
