### PR TITLE
refresh site for 2016.49

### PR DESCRIPTION
**Pull request by mystiberry-okta**
@jpf @johngronberg-okta or @rchild-okta do you want to review this before I merge it? I checked for localhost:4000 and found it only in the expected places.

### CODE REVIEW

**Comment by johngronberg-okta** [comment]
Could you update this to include #500, which reman just signed off on?

**Comment by rchild-okta** [comment]
@johngronberg-okta did you want to pull it down (with his changes) and test it out?

**Comment by mystiberry-okta** [comment]
will update this PR.

**Comment by johngronberg-okta** [comment]
found a bug when manually testing #500 so we'll leave it out of this release.

**Comment by mystiberry-okta** [comment]
reverting per John's request.

**Pull request merged**
