### PR TITLE
updates to provisioning section for SCIM

### PR DESCRIPTION
**Pull request by dhorvath**
I'm not the best w/ tables. Is there a way to put text on different lines within the tables? could not find a way to do this.

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
You can have let the line run long and it'll still format correctly: http://developer.okta.com/docs/api/resources/users.html#user-properties

but if you have lines and lines of text, it's better to organize another way, either with footnote-style numbers or something similar....

**Comment by dhorvath** [comment]
Hi Mysti,

Any way you can take a quick pass at formatting this? I trust your
expertise :)

**Comment by mystiberry-okta** [comment]
Yes! it'll be good practice for working with other people's branches in git.


Mysti


________________________________

**Comment by dhorvath** [comment]
awesome! thanks much

**Comment by dhorvath** [comment]
any idea on when you'll be able to push this?

**Comment by dhorvath** [comment]
thanks for the help!

**Comment by mystiberry-okta** [comment]
I'm looking at it right now.


Mysti


________________________________

**Comment by dhorvath** [comment]
hi @mystiberry-okta think my updates are all here and ready to go. please push when you can. thanks!

**Comment by mystiberry-okta** [comment]
looks good! Will rebuild the site by 11am.

**Pull request merged**
