### PR TITLE
Update okta_expression_lang.md

### PR DESCRIPTION
**Pull request by gabrielsroka**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
These changes look good. Do you want me to merge?

**Comment by mystiberry-okta** [comment]
@gabrielsroka should I merge this?

**Comment by gabrielsroka** [comment]
Yes.

**Comment by mystiberry-okta** [comment]
@raphaellondner-okta Can you sanity-check the expression changes (the heading changes are fine) before I merge this? Gabriel was kind enough to improve them, just want a second set of eyes since I am a newer user of our EL.

**Pull request merged**
