### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by danmarma-okta**
Very minor update

## Description:
- Updated one sentence in the hashing algorithm section.

### Resolves:
*N/A

### CODE REVIEW

**Comment by bdemers** [comment]
Seems fine to me, more word smithing then spell correcting though.

**Comment by nbarbettini** [comment]
I agree w/ @jakubvul - that's a simpler way of getting the point across.

**Comment by mystiberry-okta** [comment]
@natebarbettini-okta or @jakubvul  just to verify, bcrypt is the only hashing function we use for anything?

**Comment by nbarbettini** [comment]
@mystiberry-okta @jakubvul My understanding is: bcrypt is the only hashing function allowed for password **import**. We should double check this with the UD team and then merge this change.

**Comment by mystiberry-okta** [comment]
Confirmed w/auth team.

**Comment by nbarbettini** [comment]
Thanks @mystiberry-okta! I think we should go with Jakub's suggestion and then merge it.

**Pull request merged**
