### PR TITLE
Edits to Provisioning section

### PR DESCRIPTION
**Pull request by tgu-okta**
Rename "Java Connector" to "Java SDK", which is the official terminology. Update descriptions to be clearer.

### CODE REVIEW

**Comment by tgu-okta** [comment]
@dhorvath - check out my edits to the Provisioning section and please give a thumbs up. thanks!

**Comment by dhorvath** [comment]
Just checked out the edits. Looks good Tim! thumbs up

**Comment by tgu-okta** [comment]
@joelfranusic-okta - can you or someone else do the merge?

**Comment by joelfranusic-okta** [comment]
LGTM :ship:

**Pull request merged**
