### PR TITLE
Call out that redirect URIs may not contain a fragment component.

### PR DESCRIPTION
**Pull request by danielzeller-okta**
Docs pr for https://github.com/okta/okta-core/pull/17282

Primary Reviewers: @yuliu-okta @mystiberry-okta 
@federations-okta

### CODE REVIEW

**Comment by yuliu-okta** [comment]
LGTM 🚢

**Comment by larsjohansen-okta** [comment]
🐩

**Comment by mystiberry-okta** [comment]
Will our developer-customers know what this means? And can they get around the limitation by properly encoding the fragment?

**Comment by mystiberry-okta** [comment]
I ask about the encoding because I read Appendix B in the spec and got confused :)

**Comment by danielzeller-okta** [comment]
I considered linking to [this](https://tools.ietf.org/html/rfc6749#section-3.1.2) part of the spec here, but ultimately decided not to. I would expect a developer to understand what this means though and be able to find out in < 5 minutes if not.

**Comment by mystiberry-okta** [comment]
Works for me! Can I merge now or should it wait for .45?

**Comment by danielzeller-okta** [comment]
This will be going out with .45, so hold off for now

**Pull request merged**
