### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
lines 1356 & 1357:
- [Update Profile - Strict (PUT)](#update-profile)
- [Update Profile - Partial (POST)](#update-profile-1)

will probably need new anchors since i renamed sections on lines 1386 & 1487 (because they were both called "Update Profile"

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@gabrielsroka should I merge this? Not sure if it's complete, and if the features should be mentioned in the doc yet. thanks!

**Comment by karlmcguinness-okta** [comment]
I didn't merge as I wasn't sure we wanted to doc this way. I think the feedback here is that we need to do a better job explaining POST vs PUT but not sure the best way to document going forward.  This problem exists for other resourcees

**Comment by mystiberry-okta** [comment]
@karlmcguinness-okta Is this on my plate to drive to resolution, or...? Thanks!

**Comment by mystiberry-okta** [comment]
Closing this and moved issue to https://oktainc.atlassian.net/browse/OKTA-86407

**Pull request closed without merging**
