### PR TITLE
web-i-fication of existing content being distrubited via PDF (#1440)

### PR DESCRIPTION
**Pull request by mystiberry-okta**
* web-i-fication of existing content being distrubited via PDF

* fixes error from missing img for pull request 1440

* fixed some links that travis didn't like for #1440

* more link fixes because travis is good #1440

* missed a few more bad links

* Address concerns from review and port Embedded OCC Guide

* typo and removed percentages from common events table

* remove static oktapreview references

* update bad link

* duplicate #1509 so i can pass travis ci

## Description:
- Describe your changes. This will most likely be a copy-paste of your commit
  message(s), which should be descriptive and informative.

### Resolves:
strange weekly behavior.

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
Closing this PR since the changes are already in `source`. We can keep the `weekly` branch in the background (no open PR for it).

**Comment by mystiberry-okta** [comment]
@jmelberg-okta When you closed this PR the weekly branch on origin disappeared. That's why I repushed. Is there another solution?

**Comment by jmelberg-okta** [comment]
Weekly still exists, there just isn't an open PR for it. You can see if you navigate to: [weekly](https://github.com/okta/okta.github.io/tree/weekly). We just **cannot** delete the branch though.

**Comment by mystiberry-okta** [comment]
No, seriously, git CL was telling me it didn't exist, and Ed John couldn't find it either. sigh.

**Pull request closed without merging**
