### PR TITLE
Changes to remove the references to ON_NETWORK and OFF_NETWORK

### PR DESCRIPTION
**Pull request by rpamidimarri-okta**
Related to OKTA-173191
Bacon: test

## Description:
- Remove the support for ON_NETWORK and OFF_NETWORK in policy API.

NOTE: npm start fails locally and could not build the local version of the site. Will investigate that before merging this in.

### Resolves:
* [OKTA-173191](https://oktainc.atlassian.net/browse/OKTA-173191)

@jakubvul @eklein-okta @dannavarro-okta @richardblaylock-okta please review

### CODE REVIEW

**Comment by dannavarro-okta** [comment]
Is there a concept of in zone vs out of zone. Based on this diff I don't see that explained, but the removals look good

**Comment by rpamidimarri-okta** [comment]
We use "include" and "exclude" in other places in our API - in users, groups, etc. So, this concept is not unique to network condition in policies. In all other places, we just point out that "include" means the array of entities that need to be included. 
I dont know if we need to add any other information here about include/exclude for zones. 
@jakubvul thoughts?

**Comment by rpamidimarri-okta** [comment]
@eklein-okta - Was discussing with @jakubvul about this question ^ looks like I need to get a sign-off from you on this PR since you work with Adaptive? Can you please confirm?

**Comment by eklein-okta** [comment]
All cool with me...

**Pull request merged**
