### PR TITLE
Fix markdown syntax

### PR DESCRIPTION
**Pull request by lindsaybrunner-okta**

### CODE REVIEW

**Comment by mraible** [comment]
@rchild-okta Is it possible for me to do this? If so, do I have to fork @lindsaybrunner-okta's fork to make it all work?

**Comment by rchild-okta** [comment]
Oh, good question, I didn't notice that this came from @lindsaybrunner-okta's branch. I'm guessing you would (or she could grant you write permissions to her repo and you could do it there).

**Comment by mraible** [comment]
@rchild-okta I believe GitHub allows collaborations on PRs, but since I'm not a member of the okta org, I can't do it. Do you see the ability to do it?

**Comment by rchild-okta** [comment]
What do you mean by collaboration? Not sure if I know about that feature, other than the idea of trying to pull her branch down, making changes, and then pushing it again (which would update this PR).

**Pull request merged**
