### PR TITLE
Design Principles Blog Post

### PR DESCRIPTION
**Pull request by jtodd-okta**
image

### CODE REVIEW

**Comment by jtodd-okta** [comment]
@zdevil & @joelfranusic-okta This is pushed to master but I'm not seeing the post show up on the site. In my experience github pages normally take less than a minute to refresh and it's been about 20min, any idea what's going on?

**Comment by zdevil** [comment]
@jtodd-okta We are some "unsafe" plugins, you need to checkout the master branch, compile it locally and push. Let me know if you want me to do that.

**Comment by jtodd-okta** [comment]
Thanks Hamza, are you on some form of chat like gchat where we could sync on this a bit more? I have the instructions on how to do this and have a working build but I'm also noticing that there are 20 other files which have changes when I rsync. Do you have outstanding edits that need to go live?


________________________________

**Comment by zdevil** [comment]
I don't have anything pending.
Emailed you a HipChat room url.

**Pull request merged**
