### PR TITLE
Add Discourse comment support

### PR DESCRIPTION
**Pull request by mraible**
## Description:

Add comment support via Discourse using the jekyll-discourse-comments plugin.

https://github.com/oblakeerickson/jekyll_discourse_comments

To test, you will need to add the following entry to your `hosts` file:

```
127.0.0.1	developer.okta.com
```

Then navigate to <http://developer.okta.com:4000/blog> after running `npm start`.

This is what a post with no comments will look like:

blog-no-comments

After adding a comment:

blog-with-comments

When you click on "Start Discussion", you'll be taken to the topic on Discourse:

blog-comments-discourse

**NOTE:** This currently posts the initial blog post under my username. We could create a "devrel" account that posts the blogs as topics. I tried inviting devrel@okta.com, but I believe this is an internal-only alias.

To modify the settings for comments, login to Discourse as an admin and go to Admin > Customize > Embedding. Below is a screenshot of current settings.

discourse-embed-settings

## Type of Pull Request:

- [ ] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [x] Functional (CSS changes, JS updates, or layout modifications)

## How Has This Been Tested?
- [x] I have built this locally and verified that it does not break existing functionality.
- [x] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers:

DexEx Team

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
@mraible Nice! Give us a little bit to work on the review. We have a few shared ideas here.

**Comment by mraible** [comment]
Something to consider: the experience isn't great when you're not logged in to Discourse.

blog-discourse-not-logged-in

The login happens inside the iframe and you have to scroll to see the login button.

discourse-login

**Comment by mraible** [comment]
Another issue: Discourse is pulling in the raw text from https://developer.okta.com/feed.xml for titles. This means that a topic title gets set to "Android Unit Testing Part II&#58; Escaping Dalvik’s Hold" instead of "Android Unit Testing Part II: Escaping Dalvik’s Hold". It also seems our feed.xml doesn't have title information, which Discourse seems to allow for in its "Key to pull discourse username from feed" setting.

**Comment by mraible** [comment]
I deleted all the posts in the "Blog Post" category today because I don't think we want me as the author on all of them. I also unchecked import from feed. This will need to be re-enabled once we figure out the best way to publish posts to Discourse.

**Comment by mystiberry-okta** [comment]
Waiting for someone to review. @jmelberg-okta or ?

**Comment by rdegges** [comment]
ping @jmelberg-okta @rchild-okta

**Comment by mystiberry-okta** [comment]
Deferring to @jmelberg-okta as I'm not well versed enough in the feature to be able to review.

**Comment by mraible** [comment]
@jmelberg-okta The reason you're getting "Error Embedding" is because you're running on localhost. If you add an `/etc/hosts` entry as described in this PR's description, it should work. I also added "localhost:4000" as an allowed host on Discourse so you don't need to do this. 

I also created the devrel account this morning and re-imported all the blog posts.

Not sure about tests.

**Comment by mraible** [comment]
@jmelberg-okta It looks like this PR is in a funky state. I deleted my fork and re-created to try to get rid of "merge" commits, but now this PR says it's from `unknown repository`. Is it possible to merge this into a branch on the main `okta.github.io` project and improve it there?

**Comment by bdemers** [comment]
Closing as moment on this has stalled.
@mraible Please feel free to reopen if needed,
We would need to re-target the PR to the new `source` branch, (and remove all of the generated bits). I volunteer to help if this one should stay open

**Pull request closed without merging**
