### PR TITLE
ignore lock files

### PR DESCRIPTION
**Pull request by richardmateosian-okta**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@richardmateosian-okta  can you merge this from the page in bacon?

**Comment by joelfranusic-okta** [comment]
I wasn't sure about this. However, the StackOverflow question "[Should Gemfile.lock be included in .gitignore?](http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore)" makes a pretty convincing case for checking the `Gemfile.lock` file into git. Perhaps we start checking Gemfile.lock into git?

**Comment by mystiberry-okta** [comment]
Sounds good.

**Comment by johngronberg-okta** [comment]
Let's close this PR since we're not going to do this.

**Pull request closed without merging**
