### PR TITLE
Attempts to remove the last group target from a UserAdmin role now re…

### PR DESCRIPTION
**Pull request by brianzuzga-okta**
…sult in an error.

API doc update that goes with the code change.

Relates-to: OKTA-90514

### CODE REVIEW

**Comment by brianzuzga-okta** [comment]
@mystiberry-okta @eklein-okta @karlmcguinness-okta @jpf @slee-okta API doc PR.  The process lists says to list you all as reviewers.

@tthompson-okta @mohitchugh-okta You two were at the API design review.

@georgekwon-okta The process said that you need to give final signoff on this.

**Comment by tthompson-okta** [comment]
Looks good to me. @mystiberry-okta might want to polish the wording, but content-wise it is correct. 🚢

**Comment by mystiberry-okta** [comment]
I asked one question and made very small style changes:

https://github.com/okta/okta.github.io/pull/253/files#diff-e03f57768e93c5b04594fb833f6e71ff

Mysti
On May 26, 2016, at 12:57 PM, Trevor Thompson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good to me. @mystiberry-okta<https://github.com/mystiberry-okta> might want to polish the wording, but content-wise it is correct. 🚢

**Comment by brianzuzga-okta** [comment]
👍 like the improved wording

**Comment by mystiberry-okta** [comment]
Will merge this when the bug fix is released. Thanks!

**Comment by brianzuzga-okta** [comment]
Bug fix merged.  It made CF this week.

**Pull request merged**
