### PR TITLE
OKTA-75653

### PR DESCRIPTION
**Pull request by larsjohansen-okta**
- Added DISABLED as an option for account linking for social auth

Primary reviewer: @mystiberry-okta @tthompson-okta 
Secondary reviewers: @federations-okta

### CODE REVIEW

**Comment by larsjohansen-okta** [comment]
I'm surprised that on idps.md#948 we already had disabled documented as an option.

**Comment by karlmcguinness-okta** [comment]
I think thats why I filed the JIRA when I was writing the doc

**Comment by tthompson-okta** [comment]
🚀

**Comment by larsjohansen-okta** [comment]
Make sense, Karl.

**Comment by larsjohansen-okta** [comment]
Corresponding code merged 04/15 before CF https://github.com/okta/okta-core/pull/13772

**Comment by mystiberry-okta** [comment]
Changes look great, I'll merge for next week's preview. @larsjohansen-okta

**Pull request merged**
