### PR TITLE
update scim doc for partner-built ea

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- Replacing "beta" with Partner-Built EA
### Resolves:
 [OKTA-163746](https://oktainc.atlassian.net/browse/OKTA-163746)

image

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@karanharibhakti-okta I need a bigger screenshot for the Partner-Built EA screenshot. I made it as big as I could without distorting it, I think it's hard to read still.

**Comment by karanharibhakti-okta** [comment]
@mystiberry-okta  Can we rephrase the last sentence of the first paragraph? Something along the lines of " Publishing in Partner-Built allows customers to easily discover your integration in the OIN and work directly with the you (The ISV) to validate and deploy your integration without Okta Interference"

**Comment by mystiberry-okta** [comment]
Absolutely!

On Apr 4, 2018, at 9:20 AM, karanharibhakti-okta <notifications@github.com<mailto:notifications@github.com>> wrote:


@mystiberry-okta<https://github.com/mystiberry-okta> Can we rephrase the last sentence of the first paragraph? Something along the lines of " Publishing in Partner-Built allows customers to easily discover your integration in the OIN and work directly with the you (The ISV) to validate and deploy your integration without Okta Interference"

**Comment by mystiberry-okta** [comment]
Will do!

**Pull request merged**
