### PR TITLE
Added example of response when enrolling optional question factor.

### PR DESCRIPTION
**Pull request by nikolaystoilov-okta**
Resolves: OKTA-91808

### CODE REVIEW

**Comment by nikolaystoilov-okta** [comment]
@mystiberry-okta @karlmcguinness-okta @slee-okta @jpf Please review the documentation change.
@authteam-okta

**Comment by karlmcguinness-okta** [comment]
I think this entire doc is missing OPTIONAL/REQUIRED feature as part of rollout of MFA enroll policy.  We shouldn't just update a single use case but rather all the enroll flows

**Comment by lilyhsiao-okta** [comment]
@karlmcguinness-okta how about we fix this first and file another Jira to add OPTIONAL/REQUIRED feature. This is a customer urgent and we'd like to address it first.

**Comment by karlmcguinness-okta** [comment]
@lilyhsiao-okta  Can't we just email this example change to the customer?  It is very confusing to partially document this without explaining the feature.  This will just add more confusion IMHO especially for an EA FF.

**Comment by lilyhsiao-okta** [comment]
@karlmcguinness-okta  we already let customer know and they agreed fixing the doc would address the issue. Let me check with support if we can lower the priority and fix the doc for enroll flows which will take longer.

**Comment by karlmcguinness-okta** [comment]
@lilyhsiao-okta have we presented them with the URL to the markdown as a temp solution?  This repo is public

https://github.com/okta/okta.github.io/blob/f4973ee79c3c770595388b4a13d94e45a86bf0f5/_source/docs/api/resources/authn.md

**Comment by mystiberry-okta** [comment]
@lilyhsiao-okta is there a status on this? Not sure whether to merge this or wait for more changes. Thanks!

**Comment by lilyhsiao-okta** [comment]
@mystiberry-okta  we're going to punt on this and add  explanation for the whole feature later.. Sorry for any confusion/delay.

**Comment by mystiberry-okta** [comment]
@lilyhsiao-okta or @nikolaystoilov-okta should I close this PR?

**Comment by lilyhsiao-okta** [comment]
@mystiberry-okta  yes please go ahead. Thanks

**Pull request closed without merging**
