### PR TITLE
major cleanup of site

### PR DESCRIPTION
**Pull request by karlmcguinness-okta**
- Removed dead code, layouts, styles, etc.
- Everything now uses the same base javascript files (via footer include) with page or layout level additions
- remove legacy ToC plugins
- made layout choice explicit.  each page must have a layout defined
- fixed CORS test script

@jpf @mystiberry-okta  this one is going to need some help with quality checking

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
Why did you delete the redirects (or were these duplicates or...)? Do we have some other way of redirecting customers with the old pages bookmarked? My practice is to leave redirects in place for 6 months at least.

**Comment by karlmcguinness-okta** [comment]
@mystiberry-okta is there a specific examples?  I tried to keep the redirects in place.  It also seems best-practice is to use https://github.com/jekyll/jekyll-redirect-from to generate the index files in the generated site vs having placeholder files in the `_source`

**Comment by mystiberry-okta** [comment]
Agreed, thought I don't know how to do that, hoping someone can teach me as I anticipate a bit of movement in the near future. Ah, just the first one is a redirect (of the content I recognize):

_docs/api/resources/okta_signin_widget.html

But maybe that one is a duplicate? Sorry about that, I didn't notice the _site in the path of all those very excellent deletions. Will follow up with @joelfranusic-okta as the site has some uncharted territory for me.

**Comment by mystiberry-okta** [comment]
I can test content on Thursday, assuming none of this is needed for .40.

**Comment by karlmcguinness-okta** [comment]
/_source/_code/javascript/okta_sign-in_widget_ref.md contains a `redirect_from` to `/_docs/api/resources/okta_signin_widget.html` which is generating the output file.  This is the only file being generated to a path with _docs.  

Is this redirect needed?  This seems like a accident as no other content is published there

**Comment by karlmcguinness-okta** [comment]
This PR also contains a bunch of fixes as well.  I would prefer to get this out ASAP.  @jpf do you have bandwidth to test before Thursday?

**Comment by joelfranusic-okta** [comment]
Yup. I've got bandwidth to test today and tomorrow.

**Comment by jpf** [comment]
LGTM

**Comment by joelfranusic-okta** [comment]
Redirects in http://localhost:4000/standards/SAML/#saml-toolkits do not seem to work?

**Comment by joelfranusic-okta** [comment]
Other than that, LGTM

**Pull request merged**
