### PR TITLE
users userid rl 600 to 2000

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- /users/userid rl 600 to 2000

### Resolves:
[OKTA-144705](https://oktainc.atlassian.net/browse/OKTA-144705)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@mraju-okta Can you approve this change?

**Comment by mraju-okta** [comment]
LGTM 🚢

**Comment by mraju-okta** [comment]
Sorry, I overlooked. I forgot to mention that rate limit increase is only for the get operations to this endpoint. The writes are still at 600.

**Comment by mystiberry-okta** [comment]
I'll redo this now.

**Comment by jakubvul-okta** [comment]
I'm confused as to the status here @mystiberry-okta.

**Comment by mystiberry-okta** [comment]
Interesting! I restored the branch, but it still created a new Doc PR instead of adding the latest commit onto this one. See https://github.com/okta/okta.github.io/pull/1462

**Pull request merged**
