### PR TITLE
Update SIW version to 2.6.0

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- Update SIW 2.6.0

### Resolves:

[OKTA-155661](https://oktainc.atlassian.net/browse/OKTA-155661)

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
@mystiberry-okta Doesn't look like this was published to our external CDN yet. Can we wait until that is live before merging this?

**Comment by mystiberry-okta** [comment]
DO NOT MERGE until published to CDN.

**Comment by mystiberry-okta** [comment]
Status: Waiting for publication to CDN.

**Comment by mystiberry-okta** [comment]
Verified on CDN: https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.6.0/css/okta-theme.css

**Pull request merged**
