### PR TITLE
Change date on docker-compose post so it comes first

### PR DESCRIPTION
**Pull request by mraible**
## Description:

Change date on docker-compose post so it comes first

Currently, it comes after my post that was published yesterday.

screen shot 2017-10-11 at 2 47 20 pm

### CODE REVIEW

**Comment by bdemers** [comment]
ugg, dates in URLs... we should probably add a redirect

```text
---
redirect_to: /some/place/great
---
```

**Comment by mraible** [comment]
Where do I add this, in the post itself, or create a new page (that matches the old page name) that redirects to this one?

**Comment by bdemers** [comment]
Option B, New page that matches the old file name, that redirects to the new one

**Comment by mraible** [comment]
Please review again @bdemers. I tried to test locally, but it redirects to https://developer.okta.com/blog/2017/10/11/developers-guide-to-docker-part-3 (which looks right), but is a 404 locally.

**Pull request merged**
