### PR TITLE
Weekly refreshed with source changes since last week

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- weekly branch being updated with current source

### Resolves:
 No JIRA, just a mtce task.

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@bdemers is this what you expected from git checkout weekly && merge source?
seems like we are just repeating some commits/steps?

**Comment by bdemers** [comment]
I though weekly already merged in?

**Comment by mystiberry-okta** [comment]
I think this is an error. Closing to retry.

**Comment by bdemers** [comment]
doh, 0 files changed :)

**Pull request closed without merging**
