### PR TITLE
change 1.3.2 > 1.2.0, fix broken links

### PR DESCRIPTION
**Pull request by mystiberry-okta**
@Ujjwalreddy-okta  and @raphaellondner-okta  Please review--did I catch all instances of 1.3.2? Did I break anything?

Also @Ujjwalreddy-okta  don't forget to send me the two links to those property files.

### CODE REVIEW

**Comment by Ujjwalreddy-okta** [comment]
Looks good to me. I updated the JIRA with the new links for the properties files -

https://github.com/okta/okta-signin-widget/blob/master/node_modules/%40okta/i18n/dist/properties/login.properties
https://github.com/okta/okta-signin-widget/blob/master/node_modules/%40okta/i18n/dist/properties/country.properties

It would be nice if we could changes these links in this commit too.

**Comment by mystiberry-okta** [comment]
Will do!

I’ve got a 4 hour block of meetings, will finish this right after that!

Mysti

On Jun 8, 2016, at 9:44 AM, Ujjwalreddy-okta <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good to me. I updated the JIRA with the new links for the properties files -

https://github.com/okta/okta-signin-widget/blob/master/node_modules/%40okta/i18n/dist/properties/login.properties
https://github.com/okta/okta-signin-widget/blob/master/node_modules/%40okta/i18n/dist/properties/country.properties

It would be nice if we could changes these links in this commit too.

**Comment by mystiberry-okta** [comment]
Added! @Ujjwalreddy-okta and @raphaellondner-okta let me know when it's okay to merge and republish web site. Also, confirm whether we need to let Support, Training, know.

**Comment by raphaellondner-okta** [comment]
I reviewed and approve the changes, thanks Mysti.

**Pull request merged**
