### PR TITLE
Optimize images and make them smaller in blog post

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
OK, I believe I've squashed appropriately. It seems strange I have to `git push origin --force` after, but maybe that's expected?

**Comment by rchild-okta** [comment]
Yep, expected since you are changing the remote head.

**Comment by mystiberry-okta** [comment]
@mraible Are you resolving these conflicts? Need any help?

**Comment by mraible** [comment]
This has already been merged. Closing.

**Pull request closed without merging**
