### PR TITLE
updated links for SCIM dev program sign up

### PR DESCRIPTION
**Pull request by dhorvath**
http://pages.okta.com/DeveloperSCIM.html

### CODE REVIEW

**Comment by mikedosenbach-okta** [comment]
Looks good to me.

**Comment by annaluo-okta** [comment]
Yeah from Google docs to Okta.com! No question for the URL change 👍 

For the page itself, should we say "a free Okta developer org" instead of "a free Okta developer tenant"? Also, the Submit button location doesn't look so good IMHO.

**Comment by dhorvath** [comment]
Thanks! Did you push changes live yet? Yes, I'm not a huge fan of this page either. Have made some design changes but will see if they actually get implemented.

**Comment by dhorvath** [comment]
@annaluo-okta not seeing the change in link go live yet? can you publish? thanks

**Comment by annaluo-okta** [comment]
@dhorvath Somehow I got a Github email notification (which should be filtered unless I'm on To: or Cc:), so I took a look on this PR, but I'm actually not involved in this change and cannot publish anything.

**Comment by dhorvath** [comment]
Hmmm, who does then?

**Comment by annaluo-okta** [comment]
@dhorvath did you create this PR? The branch looks like dhorvath:patch-10, so I guess you should merge the changes?

**Comment by dhorvath** [comment]
@annaluo-okta I don't have the ability to. in the past @mystiberry-okta or @joelfranusic-okta have merged this for me. is this possible? thanks!

**Comment by mystiberry-okta** [comment]
I can merge now and it'll show up in the next build (I can rebuild the site if you need to get it out today).
Do you also want #285 merged? Once it's merged, it'll show up in the next rebuild of the site...

**Comment by mystiberry-okta** [comment]
Who owns pages.okta.com? It's not me (though I'm happy to merge this PR). Just not sure if a rebuild of developer.okta.com also rebuilds pages.okta.com.

**Comment by dhorvath** [comment]
@mystiberry-okta yes this one and #285 also, no need to change .pages I'll get that done. any ETA on when next rebuild will happen? is there anyway to quickly push this change out? thanks!

**Comment by mystiberry-okta** [comment]
Yes, I’ll merge and republish before I leave tonight.

Mysti

On Jun 24, 2016, at 3:49 PM, dhorvath <notifications@github.com<mailto:notifications@github.com>> wrote:


@mystiberry-okta<https://github.com/mystiberry-okta> yes this one and #285<https://github.com/okta/okta.github.io/pull/285> also, no need to change .pages I'll get that done. any ETA on when next rebuild will happen? is there anyway to quickly push this change out? thanks!

**Comment by mystiberry-okta** [comment]
@dhorvath I can't merge, this has conflicts. Also, at the same time, Stephen Lee came by and asked me to make changes that conflict with yours somewhat. I tried to revert my commit, couldn't. Not sure how to untangle.

**Comment by mystiberry-okta** [comment]
@dhorvath , Kevin Gough sent me slightly different changes, so I'm going to close this and do a separate PR.

**Pull request closed without merging**
