### PR TITLE
Update project settings to solidify build

### PR DESCRIPTION
**Pull request by jtodd-okta**
* Added .ruby-version and .ruby-gemset to use a project specific version
  of ruby and gems for this project to avoid issues with environment
* Removed .rvmrc as it requires trust and .ruby-version works across
  tools
* Updated bundler file to specify the only dependencies which are needed
* Updated the documentation for build and setup to use new bundler, rvm
  model

The purpose of this change is to solidify the build process and lock down the version of ruby and the required gems so the build can be consistent on anyones machine. 

@karlmcguinness-okta @benjaminwesson-okta @zdevil  Please read through the updates to the README.md which go into more detail about the conventions being put in place. 

@karlmcguinness-okta @zdevil could you please checkout this branch and try following the detailed steps for setting up the build to see if it works for your existing env?

@vronin-okta Heads up, when you get to baconizing this build, this commit will help.

### CODE REVIEW

**Comment by karlmcguinness-okta** [comment]
gets the "works on my machine" badge.

**Comment by karlmcguinness-okta** [comment]
Question on the process.  Do we want the PR to included compiled HTML or just markdown changes and  person doing the merge will compile?  I found it annoying to review the compiled html.

**Comment by jtodd-okta** [comment]
Thanks Karl, and just to confirm did you execute with:


"bundle exec jekyll serve --watch"


As for process, I'd first love to understand in a bit more detail why we can't have github do the build. You had mentioned something about a toolbar plugin, can you point me to where that is wired up?


As for the workflow, I like the separate commit approach for now. Given that multiple PRs might be in flight, doing the build right before merge will avoid more conflicts. In the mid-term I'm hoping Victor's team can baconize this build. Tracking that here: https://oktainc.atlassian.net/browse/OKTA-58332

________________________________

**Comment by karlmcguinness-okta** [comment]
Yes `bundle exec jekyll serve --watch` is run exactly like readme and worked. 

The plugin is located in `/okta.github.io/_source/_plugins`.  This generates the left nav ToC based on headers in the markdown.  It was very slow doing this with JS at runtime and we wanted a fast static site.

**Comment by zdevil** [comment]
I followed the readme file and it works great on my machine 
Thanks Jon.

**Comment by jtodd-okta** [comment]
Awesome thanks Hamza, I've merged this to master. Let's use this process going forward.

On May 20, 2015, at 11:10 AM, Hamza Essaoui <notifications@github.com<mailto:notifications@github.com>> wrote:


I followed the readme file and it works great on my machine
Thanks Jon.

-

**Pull request closed without merging**
