### PR TITLE
Remove bad characters from HTML and code examples

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes some bad/unprintable characters.

### CODE REVIEW

**Comment by jakubvul** [comment]
@jmelberg-okta should we make that a separate PR?

**Comment by jmelberg-okta** [comment]
@jakubvul - For changes like these, we want to make sure there are tests that validate we've:

1. Caught all prior occurrences of the unprintable characters
2. Catch future unprintable characters

Any PR with a change similar to this should include tests that validate it was done properly.

**Comment by jakubvul** [comment]
On that note: https://oktainc.atlassian.net/browse/OKTA-158104

**Comment by nbarbettini** [comment]
I agree that this should be linted. The fact that our scripts are written in bash means that they can't be run or developed cross-platform unfortunately.

I'll advocate for migrating to an xplat language like node in the future.

**Pull request closed without merging**
