### PR TITLE
Fix errors on Windows

### PR DESCRIPTION
**Pull request by nbarbettini**
## Description:
The npm scripts wouldn't run under Windows because of a few issues.

Ping @rchild-okta or @jmelberg-okta for a review.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Not sure if I should PR this against origin/weekly, or a different branch. I can adjust if needed.

**Comment by nbarbettini** [comment]
(The only review this should need is making sure it still builds fine under macOS.)

**Comment by jakubvul-okta** [comment]
Still builds fine on macOS, though Travis confirmed that.

**Comment by jakubvul-okta** [comment]
@nbarbettini you'll need to rebase (aggressively) before this can be merged in.

**Comment by nbarbettini** [comment]
@jakubvul-okta I've rebased as aggressively as I know how. Ready to merge?

**Comment by rchild-okta** [comment]
@jakubvul @natebarbettini-okta FYI I don't think it's necessary to rebase in okta.github.io after the PR has started. General idea is:

1. When you're sending out a big PR, break it up into commits to make it easier to review
2. With the back and forth from comments and corrections, new commits are added
3. No need to rebase at this point since we use the squash & merge flow anyway

**Comment by nbarbettini** [comment]
@rchild-okta Not sure if this matters, but there were other, unrelated commits showing up in this PR (presumably because origin/weekly was reset and force-pushed). I assumed that was why @jakubvul-okta asked me to rebase.

**Comment by rchild-okta** [comment]
Ah, gotcha, in that case never mind!

**Comment by nbarbettini** [comment]
(I can't merge myself, can @jakubvul-okta or someone else press the button?)

**Pull request merged**
