### PR TITLE
ISV SAML App doc update

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- Update the doc for better ISV process for SAML apps.

### Resolves:

* [OKTA-127785](https://oktainc.atlassian.net/browse/OKTA-127785)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@karanharibhakti-okta , I looked for other places where this is mentioned, didn't find any. Does anything else need to be updated for this? Let me know when we want to publish this so it doesn't go out early.

**Comment by karanharibhakti-okta** [comment]
@mystiberry-okta  The ISV will need to click the Green Button "Submit Application For Review" and fill out the SAML form in order for Okta to reach out to them. Can we add those steps as well ? 

1) Click "Submit Application for Review" (ISV gets redirected to OAN Manager)
2) Fill our All general information 
3) Click On under SAML tab and fill out all of the information and click Submit. 
4) Once Submitted, ISV can track the stage their integration is in via OAN Manager.

**Comment by mystiberry-okta** [comment]
Will do, Karan.

**Comment by karanharibhakti-okta** [comment]
@mystiberry-okta  LGTM! Does it make sense to add any screenshots of OAN Manager since the admins are going to be redirected from Okta UI to a completely different UI.

**Comment by mystiberry-okta** [comment]
Yes, I'll add one more screenshot. Thanks!

**Comment by mystiberry-okta** [comment]
merging this PR so we make today's release. Adding extra screenshots in a separate PR

**Pull request merged**
