### PR TITLE
Doc policy rule type in examples in Policy API

### PR DESCRIPTION
**Pull request by mpeng-okta**
## Description:
- Adds the `type` property to the policy rule object examples
- It's already documented elsewhere in the Policy API--adding to these examples because they just happen to lack that property

### Resolves:
* [OKTA-141467](https://oktainc.atlassian.net/browse/OKTA-141467)

### CODE REVIEW

**Comment by mpeng-okta** [comment]
@mystiberry-okta do you have any idea about why the /push build is failing? I don't think my changes should have anything to do with the errors, but I'm not sure what's wrong.

**Comment by srinivasanagandla-okta** [comment]
🚢

**Comment by mystiberry-okta** [comment]
Restarting the first test to see if it'll pass now.

**Comment by mystiberry-okta** [comment]
@mpeng-okta  Following up with team to find out if we need to rebase again.

**Comment by mpeng-okta** [comment]
@mystiberry-okta got it, thanks!

**Comment by mystiberry-okta** [comment]
@mpeng-okta I rebased this and as soon as tests pass, I will merge it.

**Comment by mpeng-okta** [comment]
Thanks! :)

**Pull request merged**
