### PR TITLE
Added the Okta SignIn Widget to the SDK section

### PR DESCRIPTION
**Pull request by Ujjwalreddy-okta**
OKTA-90960

screen shot 2016-06-01 at 1 34 30 pm

### CODE REVIEW

**Comment by Ujjwalreddy-okta** [comment]
@mystiberry-okta Can you please take a look at this and merge it if everything is good?

**Comment by mystiberry-okta** [comment]
@Ujjwalreddy-okta dumb question but should the title be Okta Sign-In Widget? I'm not sure if this is an official feature name (so we have to protect copyright by including the whole name).

**Comment by mystiberry-okta** [comment]
I'll merge as soon as you verify that the title "Sign-In Widget" is okay (or change to add Okta).

**Comment by Ujjwalreddy-okta** [comment]
@mystiberry-okta Let me confirm that; will let you know soon.

**Comment by Ujjwalreddy-okta** [comment]
@mystiberry-okta Let's go with `Okta Sign-In Widget`

**Comment by mystiberry-okta** [comment]
@Ujjwalreddy-okta I changed the title to include Okta, can you verify and let me know if okay to merge? If not now (site will be rebuilt tomorrow, most likely), when?  THANKS!

**Comment by Ujjwalreddy-okta** [comment]
LGTM 🚢

**Comment by mystiberry-okta** [comment]
will build tomorrow morning! Yay!

**Pull request merged**
