### PR TITLE
Add CLA to developer.okta.com

### PR DESCRIPTION
**Pull request by joelfranusic-okta**
- ADD CLA PDF
- Moved the 'legal_notice' template to 'plain'
- Move 3rd Party Notices to 'plain' template (and cleanup some technical debt in the process)

### CODE REVIEW

**Comment by joelfranusic-okta** [comment]
Note: In addition to adding the CLA, this commit cleans up a lot of the "3rd party notices" and moves them to use the same "plain" layout as the CLA page does.

**Comment by joelfranusic-okta** [comment]
@mystiberry-okta @johngronberg-okta for your review.

Staged here: http://frozen-ridge-22271.herokuapp.com/cla/

**Comment by johngronberg-okta** [comment]
If this is the same as I reviewed last night, lgtm


________________________________

**Comment by joelfranusic-okta** [comment]
@johngronberg-okta yes, this is the same as you reviewed.

**Comment by mystiberry-okta** [comment]
In an ideal world we'd change "would be" to "is" at the bottom of index.md, however, I'm guessing this has been vetted by legal so I didn't touch it. @joelfranusic-okta I'd happily make the change but only if you say it's okay. Otherwise, ready to merge.

**Pull request merged**
