### PR TITLE
Add metadata HAL link changes

### PR DESCRIPTION
**Pull request by royalchan-okta**
## Description:
- Add the oidc well-known endpoint to the AS metadata HAL link

## Type of Pull Request:

- [x] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [ ] Functional (CSS changes, JS updates, or layout modifications)

### Resolves:
* [OKTA-124562](https://oktainc.atlassian.net/browse/OKTA-124562)

## How Has This Been Tested?
- [ ] I have built this locally and verified that it does not break existing functionality.
- [ ] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers:

- @larsjohansen-okta @mystiberry-okta 

- [Blog Post Google Doc](https://docs.google.com)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@royalchan-okta We don't need changes here, do we? http://developer.okta.com/docs/api/resources/oidc.html#openid-connect-discovery-document

**Comment by royalchan-okta** [comment]
@mystiberry-okta nope, this is specific to Auth Servers

**Comment by mystiberry-okta** [comment]
@rchild-okta or @jmelberg-okta can you help us untangle this Doc PR? My 2017.20 weekly updates showed up in this PR, I'm not sure when that happened or why.

**Comment by rchild-okta** [comment]
@mystiberry-okta - When you deployed the weekly build, step 9 of the [deploy process](https://gist.github.com/rchild-okta/48d8649f610697cfd0266b24d0808c4b#you-are-deploying-the-weekly-branch) was not followed. This means that the weekly branch is not in sync with master, and there are now extra commits that have been added in - Ed's and Jordan's.

What needs to happen:

1. Rebase weekly on master. With Step 9, you would normally not have to do this, but because of the extra commits it has to be hand rolled. In the rebase, you will see all the commits from f52b397 to 9367537. In the interactive rebase editor, remove f52b397 to 1838cf4.

2. Verify that this looks correct via git log. The correct state is that weekly has all the commits from master (up until 5c8145e), with the two extra commits that have not been deployed to prod (Ed's and Jordan's).

3. Force push it to the weekly branch

At this point, weekly will be in the correct state - it **must** be reset after the deploy (step 9) so that it is in sync with master for any new incoming commits.

When there is a PR that has been rebased off of the old weekly, the committer just needs to rebase off of latest weekly to pull in anything that's changed. In the case of this PR, that means that once weekly has been rebased following the above 3 steps, Royal will just need to rebase off of weekly and repush, and at that point we'll only see his one commit.

**Comment by rchild-okta** [comment]
I went ahead and did those 3 steps since we'll all be out at a conference tomorrow. Weekly is currently in the right state.

Next step: @royalchan-okta just needs to rebase off of latest origin/weekly and repush to this branch, and the extra commits will be out and it can be merged into weekly.

**Comment by mystiberry-okta** [comment]
It was not followed because we had a merge into weekly and the instructions didn't say what to do in that case, only that we shouldn't force push.

Mysti

On May 21, 2017, at 9:22 AM, rchild-okta <notifications@github.com<mailto:notifications@github.com>> wrote:


@mystiberry-okta<https://github.com/mystiberry-okta> - When you deployed the weekly build, step 9 of the deploy process<https://gist.github.com/rchild-okta/48d8649f610697cfd0266b24d0808c4b#you-are-deploying-the-weekly-branch> was not followed. This means that the weekly branch is not in sync with master, and there are now extra commits that have been added in - Ed's and Jordan's.

What needs to happen:

  1.  Rebase weekly on master. With Step 9, you would normally not have to do this, but because of the extra commits it has to be hand rolled. In the rebase, you will see all the commits from f52b397<https://github.com/okta/okta.github.io/commit/f52b3970acdf571a9734c738ccb573ecd9dc32e6> to 9367537<https://github.com/okta/okta.github.io/commit/936753717eba5b09080d918cd2a765b7078ce2ee>. In the interactive rebase editor, remove f52b397<https://github.com/okta/okta.github.io/commit/f52b3970acdf571a9734c738ccb573ecd9dc32e6> to 1838cf4<https://github.com/okta/okta.github.io/commit/1838cf470d3b17044a4c3ee68312a997bc534e83>.

  2.  Verify that this looks correct via git log. The correct state is that weekly has all the commits from master (up until 5c8145e<https://github.com/okta/okta.github.io/commit/5c8145e4f986e0e33a5021b16a8b3e30c99b8386>), with the two extra commits that have not been deployed to prod (Ed's and Jordan's).

  3.  Force push it to the weekly branch

At this point, weekly will be in the correct state - it must be reset after the deploy (step 9) so that it is in sync with master for any new incoming commits.

When there is a PR that has been rebased off of the old weekly, the committer just needs to rebase off of latest weekly to pull in anything that's changed. In the case of this PR, that means that once weekly has been rebased following the above 3 steps, Royal will just need to rebase off of weekly and repush, and at that point we'll only see his one commit.

**Comment by royalchan-okta** [comment]
I've rebased on new weekly

**Pull request merged**
