### PR TITLE
92937 tr toc scroll position

### PR DESCRIPTION
**Pull request by flickerbox-tom**
## Description:
- Update TOC scroll position so it is not covered by the footer when someone scrolls to the bottom of the page on smaller browser heights.

### Resolves:
* [Issue #X](#X)

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
If you rebase on master, this should now pass the travis tests.

**Comment by mystiberry-okta** [comment]
This needs to be rebased on master to get rid of the unrelated commits. Please do this by Thursday night to avoid even more rebasing, or close this PR if it's not going in. Thanks!

**Comment by flickerbox-tom** [comment]
The branch was rebased on master and pushed up to git earlier. Does the rebase need to squash commits? Would it make sense to redo this change in a fresh branch off of weekly and redo the pull request?

**Comment by mystiberry-okta** [comment]
That's fine if that's easier for you! The commits are squashed when we merge, but of course if you want to squash them, that's fine too.

**Pull request closed without merging**
