### PR TITLE
Changes for well known endpoint for API access management

### PR DESCRIPTION
**Pull request by ashishgupta-okta**
Changes for well known endpoint for API access management

@larsjohansen-okta @mystiberry-okta 
@federations-okta

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@ashishgupta-okta I don't understand these changes (id_token token?). Should I?

**Comment by mystiberry-okta** [comment]
@ashishgupta-okta Should this be merged for release .47?

**Comment by larsjohansen-okta** [comment]
@ashishgupta-okta can you provide screenshots of your changes?

**Comment by larsjohansen-okta** [comment]
Realized there would be a lot of screenshots, so nevermind. It looks good to me. 🚢

**Pull request merged**
