### PR TITLE
Update with PR from @AlexeySoshin 

### PR DESCRIPTION
**Pull request by mraible**
See https://github.com/oktadeveloper/okta-spring-boot-saml-example/pull/2 for details.

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@mraible Do you want me to test,merge,publish for Wed. 4/19 site refresh?

**Comment by mraible** [comment]
@mystiberry-okta Yes, please!

**Comment by mraible** [comment]
@mystiberry-okta I don't see this update reflected on http://developer.okta.com/blog/2017/03/16/spring-boot-saml. Do you know why it's not there?

**Comment by mystiberry-okta** [comment]
Be a few more minutes.

**Pull request merged**
