### PR TITLE
update postman oauth hotfix

### PR DESCRIPTION
**Pull request by mystiberry-okta**
## Description:
- Update oauth postman collection hotfix

## Type of Pull Request:

- [x] Content (Documentation updates or typo-fixes)
- [ ] Blog Post
- [ ] Functional (CSS changes, JS updates, or layout modifications)

### Resolves:
* [OKTA-118042](https://oktainc.atlassian.net/browse/OKTA-118042)

## How Has This Been Tested?
- [x] I have built this locally and verified that it does not break existing functionality.
- [ ] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [ ] For functional changes, I have added tests.

## Primary Reviewers:
@gronberg or @cwu-okta

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
@johngronberg-okta or @cwu-okta Can you review? I wasn't able to refresh the collection using the old collection ID, so updated it here and tested locally that it brings in the new collection. Will delete the old collection link as soon as we publish this.

**Comment by johngronberg-okta** [comment]
you also need to update the collection at /docs/api/getting_started/api_test_client.html

**Comment by johngronberg-okta** [comment]
as well as oauth-clients.md

**Comment by mystiberry-okta** [comment]
@johngronberg-okta Updated.

**Comment by mystiberry-okta** [comment]
@johngronberg-okta Note that I am moving the api template out of _source because it builds and we don't want it to. I'll link to it from the wiki (maybe a zip file or something) instead.

**Pull request merged**
