### PR TITLE
Describe form of allowable custom scopes.

### PR DESCRIPTION
**Pull request by danielzeller-okta**
Link to spec defining acceptable scopes.

Primary reviewer: @yuliu-okta 
@federations-okta 

Related to: OKTA-95050

### CODE REVIEW

**Comment by danielzeller-okta** [comment]
Code pr: https://github.com/okta/okta-core/pull/15333

**Comment by mystiberry-okta** [comment]
@danielzeller-okta One question: I read the spec referenced, found their example hard to understand. Could be it's my ignorance in this area, but wondering if we need to give customers a little more help here?  Also, should we mention they can't use < or >, or we intend to fix this soon.

**Comment by danielzeller-okta** [comment]
@mystiberry-okta the spec is basically just defining a range of acceptable characters in hexadecimal. I don't think we need to provide further guidance in this because if they find their scopes not being valid they are using some _really_ strange characters.

As for point 2 yes thank you for reminding me. It's not that `<` **or** `>` is disallowed, it's `<` **and** `>` that isn't allowed (in any order). I'm not sure how we should best surface that detail. I'd greatly appreciate you owning that change :)

**Comment by yuliu-okta** [comment]
Do we really need to mention a parameter must follow the spec? We do not do that for all others. It seems to me that if we do not want to mention the exception of <>, then the doc change is not needed.

**Comment by danielzeller-okta** [comment]
@yuliu-okta Karl would like us to call out the <> exception

**Comment by mystiberry-okta** [comment]
@danielzeller-okta did I capture the < > restriction correctly?

**Comment by danielzeller-okta** [comment]
@mystiberry-okta almost. Either `<` or `>` are fine, but BOTH are not allowed in any order.

**Comment by mystiberry-okta** [comment]
Okay, @danielzeller-okta , I captured either but not both in the comment. Please review. Thanks!

**Comment by danielzeller-okta** [comment]
LGTM @mystiberry-okta 🍧

**Comment by mystiberry-okta** [comment]
Just waiting to merge until .29 is pushed next week, to go with OKTA-95050. Let me know if it can go sooner.

**Pull request merged**
