### PR TITLE
Moves markdown lint tests into Node script

### PR DESCRIPTION
**Pull request by jmelberg-okta**
## Description:
- Moves basic markdown lint checks into a separate Node script

This PR is broken into two commits:
1. [4ff09f0](https://github.com/okta/okta.github.io/pull/2159/commits/4ff09f08f68354d70ee25ad48c702ba42b544e96) - Move lint checks to a Node script
2. [d392c81](https://github.com/okta/okta.github.io/pull/2159/commits/d392c81405991541e7492120231fe5f7baed0905) - Removed bad strings/characters

### Resolves:
* Partially resolves issue #2136, moving all `*.md` lint checks into a separate command

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
@rdegges & @aaronpk - FYI - We're modifying a few `/blog` and `/books` pages here to remove bad characters. For example:

- `“` and `”`are replaced with `"`
- `‘` and `’` are replaces with `'`
- `…` is replaced with `...`

Is this ok? If needed, we can omit them from our script

**Comment by aaronpk** [comment]
why are curly quotes "bad"?

**Comment by jakubvul** [comment]
@aaronpk because they're non-ASCII and Github gets weird when rendering files with non-ASCII characters. Specifically, Github breaks formatting under the “change view” when smart quotes are used. When Jekyll converts the markdown to HTML, all straight quotes are converted to smart quotes.

**Comment by aaronpk** [comment]
I don't mind using straight quotes in the book pages. But if GitHub is breaking on non-ASCII characters I think that's GitHub's fault and they should fix it. There's a lot of useful characters outside the ASCII set...

**Pull request merged**
