### PR TITLE
scim update

### PR DESCRIPTION
**Pull request by mystiberry-okta**

### CODE REVIEW

**Comment by mystiberry-okta** [comment]
Resolves: OKTA-120747
test: bacon

**Comment by mystiberry-okta** [comment]
tested and ready to merge.

**Comment by yumingcao-okta** [comment]
is the plan to have the OAN Manager button added in this PR also?

**Comment by mystiberry-okta** [comment]
@karanharibhakti-okta please answer the question, and whether this doc is complete or needs to refer to the green button.

**Pull request closed without merging**
