### PR TITLE
Update System Log Docs

### PR DESCRIPTION
**Pull request by guyzehavi-okta**
Currently the documentation does not reflect some of the additions we have made to the API. This change brings the docs in line with the API changes.

Resolves: OKTA-106368

### CODE REVIEW

**Comment by guyzehavi-okta** [comment]
Reviewer is @mystiberry-okta

**Comment by guyzehavi-okta** [comment]
Thanks for the quick turnaround @mystiberry-okta . I made the changes per your comment (changing references from 'rain-admin.okta1.com:1802' to 'MyOrg.okta.com' )

**Comment by mystiberry-okta** [comment]
Looks great, @guyzehavi-okta 🚢 , so I'll merge and publish wed.

**Comment by guyzehavi-okta** [comment]
Thank you @mystiberry-okta .

**Pull request merged**
