### PR TITLE
Changing 'backward compatible' to 'backwards compatible'

### PR DESCRIPTION
**Pull request by jakubvul**
Only found one instance of the former, so we can now say that we use it totally consistently!

### CODE REVIEW

**Comment by jakubvul** [comment]
As far as usage goes, "backwards" still wins though: https://trends.google.ca/trends/explore?date=all&q=%22backward%20compatible%22,backwards%20compatible

**Comment by jakubvul** [comment]
Google search finds them pretty close: ~414,000 for "backward compatible" and ~470,000 for "backwards compatible".

More importantly, since they're basically equivalent, why not just stick with the one everyone's been using up to this point, which is "backwards"?

**Comment by mystiberry-okta** [comment]
Agree!

**Comment by jakubvul** [comment]
Sorry, I didn't notice that you said you only found one instance of each, which makes my comment that we should stick with what we've been using up to this point confusing. So this is what I found:

```
Searching 2366 files for "backwards compatible"

/Users/jakubvul/code/okta/okta.github.io/_source/_docs/api/getting_started/releases-at-okta.md:
   28  |:------------|:------------------:|:-----------------:|:---:|:---:|:---:|
   29  | Contact with Product Team  |     X             |                   |       |       |       |
   30: | API  Changes               | Subject to change | Subject to change | Backwards compatible  | Backwards compatible   | N/A   |
   31  | Okta Support               |                   |                      | X   | X   |     |
   32  | Service-level agreements   |                   |                      | X   | X   | X   |
   ..
   64  
   65  * Are supported by Okta Customer Support.
   66: * Obey the platform SLAs. APIs are [backwards compatible](/docs/api/getting_started/design_principles.html).
   67  
   68  >Note: A platform feature may skip EA if it doesn't affect other features or functionality. 

/Users/jakubvul/code/okta/okta.github.io/_source/_posts/2015-05-08-software-engineering-design-principles.md:
  131  * Incremental rollout first to test accounts and then in batches of customers
  132  * Automated deployment process
  133: * Code and infrastructure is forwards and backwards compatible allowing
  134    rollback
  135  * Health check and automatically remove down nodes

/Users/jakubvul/code/okta/okta.github.io/_source/_standards/OAuth/index.md:
    8  # OAuth 2.0 and Okta
    9  
   10: OAuth 2.0 is the next evolution of the OAuth protocol and is not backwards compatible with OAuth 1.0. 
   11  OAuth 2.0 focuses on client developer simplicity while providing specific authorization flows for web applications, desktop applications, mobile phones, and living room devices.
   12   

/Users/jakubvul/code/okta/okta.github.io/_source/_standards/SCIM/index.md:
 1157  **What are the differences between SCIM 1.1 and 2.0?**
 1158  
 1159: * Namespaces:  Namespaces are different, therefore 2.0 is not backwards compatible with 1.1
 1160  
 1161      | SCIM 1.1 | SCIM 2.0 |

6 matches across 4 files
```

**Pull request merged**
