### PR TITLE
Adding VWO Script

### PR DESCRIPTION
**Pull request by rdegges**
## Description:
- Describe your changes. This will most likely be a copy-paste of your commit
  message(s), which should be descriptive and informative.

### Resolves:
* [Issue #X](#X)

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by flickerbox-tom** [comment]
This is not a tracking script. It is for A/B testing across www and developer properties. 

Because of the nature of page loading and content changes in the variant tests the script needs to load in head in same way the is advised for Optimizely or Google Optimize.
https://vwo.com/

**Comment by rdegges** [comment]
Ugh. I just read this.

**Comment by rdegges** [comment]
will re-issue a PR to fix, sorry!

**Comment by flickerbox-tom** [comment]
Thanks

**Pull request merged**
