### PR TITLE
Public role listing API to adapt with Role-to-Group Assignment

### PR DESCRIPTION
**Pull request by alifatolahi-okta**
> NOTE: Merge #2746 first, before merging this!

## Description:
- Public role listing API to adapt with Role-to-Group Assignment
- https://oktawiki.atlassian.net/wiki/spaces/eng/pages/636519035/Admin+Role-to-Group+Assignment+API+Design
- Monolith PR: https://github.com/okta/okta-core/pull/32450

### Resolves:

* [OKTA-211581](https://oktainc.atlassian.net/browse/OKTA-211581)

Screenshots of the updated Docs:
screen shot 2019-02-08 at 1 57 35 pm
screen shot 2019-02-08 at 1 57 29 pm
screen shot 2019-02-08 at 1 57 12 pm
screen shot 2019-02-08 at 1 59 49 pm

cc: @okta/flm @rchild-okta

### CODE REVIEW

**Comment by bdemers** [comment]
Revert the `package-lock.json` changes too please.

The content looks good to me 👍 but @motikagan-okta should probably chime in too

**Comment by alifatolahi-okta** [comment]
@bdemers dropped the `package-lock.json` changes and yes I will not merge until feature is GAed.

**Comment by jakubvul** [comment]
@bdemers and @alifatolahi-okta GA in Preview is GA, from a dev doc perspective.

**Comment by alifatolahi-okta** [comment]
We can ignore this PR now because I've already merged everything into one PR: https://github.com/okta/okta.github.io/pull/2746

**Comment by alifatolahi-okta** [comment]
We can ignore this PR now because I've already merged everything into one PR: #2746

**Pull request closed without merging**
