### PR TITLE
Adds release filter for event type catalog.

### PR DESCRIPTION
**Pull request by bobtiernay-okta**
## Description:

In order to aid users in finding new event types by release, this PR adds a release filter to the [event type catalog page](https://developer.okta.com/docs/api/resources/event-types) to supplement the existing live search.

### Page Context
image

### Control
Unique release numbers, sorted descending with "All Releases" selected by default
image

### Deep Linking
Respects URL params and syncs as you change:

image

### Dependencies
Note that there is no dependency on a Monolith release

### Resolves:

* [OKTA-210257](https://oktainc.atlassian.net/browse/OKTA-210257)

### CODE REVIEW

**Comment by jakubvul** [comment]
@bobtiernay-okta why is there a 2019.04.1?

**Comment by bobtiernay-okta** [comment]
I believe that's when a developer added it. If that's not the case, we would need to update upstream.

**Comment by bobtiernay-okta** [comment]
@jakubvul https://github.com/okta/okta-core/blame/master/components/core/events/api/src/main/java/com/okta/monolith/core/events/types/v2/EventTypeV2.java#L652

**Comment by bobtiernay-okta** [comment]
Also, it exists today: https://developer.okta.com/docs/api/resources/event-types?q=2019.04.1

**Comment by bobtiernay-okta** [comment]
@yumingcao-okta Do you have any comment on what this value should be?

**Comment by yumingcao-okta** [comment]
@bobtiernay-okta We meant to set the value for release 4th week of 2019, that's when the feature went to Beta.

**Comment by jakubvul** [comment]
I think the long and short of this is that we can't be showing changes that are scheduled for 2 months in the future.

**Comment by bobtiernay-okta** [comment]
Agreed. I think it's orthogonal to this change though. But It's something we should work through with @jessstarr-okta who is leading that effort. There are controls we can put in place both upstream (in monolith) and downstream (in docs) to help with this.

**Comment by bobtiernay-okta** [comment]
Updated to the correct versions here:

image

Will also correct upstream.

**Comment by bobtiernay-okta** [comment]
Fixed the bad release values in https://github.com/okta/okta-core/pull/32636

**Comment by bretterer** [comment]
I think I would rather hold on this feature until the new VuePress site is released.

**Comment by bobtiernay-okta** [comment]
@bretterer Not sure I understand. Mind clarifying?

**Comment by bretterer** [comment]
@bobtiernay-okta we are in the process of migrating away from Jekyll in favor of VuePress.... we are close to doing the final push to migrate over and a lot of work has already been done.  I am suggesting that we hold off on making this change until we can make it in VuePress.

**Comment by bobtiernay-okta** [comment]
That's fair. When do you expect that to be finalized?

**Comment by bobtiernay-okta** [comment]
@bretterer Following up, thanks.

**Comment by bretterer** [comment]
@bobtiernay-okta Soon(tm)   

Not sure of the date, but we are in the final stretch of it.  A few bugs within VuePress itself are causing a little bit of a delay.

**Comment by bretterer** [comment]
Thank you for this PR to help improve our documentation. As you may know, we have moved our developer documentation to a new repo.

Since this PR is targeting our developer docs, we are requesting that you migrate this PR over to the new repo https://github.com/okta/okta-developer-docs

If you have any questions about this, or need assistance with a complex PR, please let us know in #eng-devex

**Pull request closed without merging**
